# Use an official Python runtime as a parent image
FROM python:3.10

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the consumer code
COPY data_processing_microservice.py .

# Command to run the consumer microservice
CMD ["python", "data_processing_microservice.py"]
