# Use an official Python runtime as a parent image
FROM python:3.10

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install the required Python packages
RUN pip install --no-cache-dir -r requirements.txt

# Copy the producer script into the container
COPY send_data_to_kafka.py .

# Command to run the producer script
CMD ["python", "send_data_to_kafka.py"]

